[2022-09-17 19:29:45,421] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: gmailPipelineV1.gmailExtractTask scheduled__2022-09-13T00:00:00+00:00 [queued]>
[2022-09-17 19:29:45,426] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: gmailPipelineV1.gmailExtractTask scheduled__2022-09-13T00:00:00+00:00 [queued]>
[2022-09-17 19:29:45,426] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 19:29:45,426] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-17 19:29:45,426] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-17 19:29:45,434] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): gmailExtractTask> on 2022-09-13 00:00:00+00:00
[2022-09-17 19:29:45,436] {standard_task_runner.py:52} INFO - Started process 6335 to run task
[2022-09-17 19:29:45,441] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'gmailPipelineV1', 'gmailExtractTask', 'scheduled__2022-09-13T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/gmailDag.py', '--cfg-path', '/var/folders/mm/xv24gcjj46l_jx1m76p5bgy80000gn/T/tmpt20a11il', '--error-file', '/var/folders/mm/xv24gcjj46l_jx1m76p5bgy80000gn/T/tmp8kn9fz3u']
[2022-09-17 19:29:45,443] {standard_task_runner.py:80} INFO - Job 84: Subtask gmailExtractTask
[2022-09-17 19:29:45,495] {task_command.py:371} INFO - Running <TaskInstance: gmailPipelineV1.gmailExtractTask scheduled__2022-09-13T00:00:00+00:00 [running]> on host abhays-mbp.lan
[2022-09-17 19:29:45,543] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=gmailPipelineV1
AIRFLOW_CTX_TASK_ID=gmailExtractTask
AIRFLOW_CTX_EXECUTION_DATE=2022-09-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-13T00:00:00+00:00
[2022-09-17 19:29:45,739] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 25, in pullGmailExtract
    gextract =  gmailExtract(authcred=auth.getgmailAuthentication())
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/gmailAuthentication.py", line 28, in getgmailAuthentication
    gmailcreds.refresh(Request())
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/google/oauth2/credentials.py", line 302, in refresh
    ) = reauth.refresh_grant(
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/google/oauth2/reauth.py", line 347, in refresh_grant
    _client._handle_error_response(response_data)
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/google/oauth2/_client.py", line 62, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_data)
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
[2022-09-17 19:29:45,745] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=gmailPipelineV1, task_id=gmailExtractTask, execution_date=20220913T000000, start_date=20220917T232945, end_date=20220917T232945
[2022-09-17 19:29:45,754] {standard_task_runner.py:92} ERROR - Failed to execute job 84 for task gmailExtractTask (('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'}); 6335)
[2022-09-17 19:29:45,802] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-17 19:29:45,836] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
