[2022-08-29 21:46:24,479] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: gmailPipelineV1.gmailExtractTask manual__2022-08-30T01:46:20.070970+00:00 [queued]>
[2022-08-29 21:46:24,486] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: gmailPipelineV1.gmailExtractTask manual__2022-08-30T01:46:20.070970+00:00 [queued]>
[2022-08-29 21:46:24,486] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 21:46:24,486] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-29 21:46:24,486] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 21:46:24,495] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): gmailExtractTask> on 2022-08-30 01:46:20.070970+00:00
[2022-08-29 21:46:24,498] {standard_task_runner.py:52} INFO - Started process 4343 to run task
[2022-08-29 21:46:24,506] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'gmailPipelineV1', 'gmailExtractTask', 'manual__2022-08-30T01:46:20.070970+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/gmailDag.py', '--cfg-path', '/var/folders/mm/xv24gcjj46l_jx1m76p5bgy80000gn/T/tmpsur2w7co', '--error-file', '/var/folders/mm/xv24gcjj46l_jx1m76p5bgy80000gn/T/tmp6qo_j3rd']
[2022-08-29 21:46:24,508] {standard_task_runner.py:80} INFO - Job 65: Subtask gmailExtractTask
[2022-08-29 21:46:24,553] {task_command.py:371} INFO - Running <TaskInstance: gmailPipelineV1.gmailExtractTask manual__2022-08-30T01:46:20.070970+00:00 [running]> on host abhays-mbp.lan
[2022-08-29 21:46:24,601] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=gmailPipelineV1
AIRFLOW_CTX_TASK_ID=gmailExtractTask
AIRFLOW_CTX_EXECUTION_DATE=2022-08-30T01:46:20.070970+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-30T01:46:20.070970+00:00
[2022-08-29 21:46:24,617] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2022-08-29 21:46:37,886] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 26, in pullGmailExtract
    if gextract.extractUnreadEmails():
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/gmailExtract.py", line 39, in extractUnreadEmails
    __, frmEmail = frm.replace(">",'').split(" <")
ValueError: not enough values to unpack (expected 2, got 1)
[2022-08-29 21:46:37,891] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=gmailPipelineV1, task_id=gmailExtractTask, execution_date=20220830T014620, start_date=20220830T014624, end_date=20220830T014637
[2022-08-29 21:46:37,899] {standard_task_runner.py:92} ERROR - Failed to execute job 65 for task gmailExtractTask (not enough values to unpack (expected 2, got 1); 4343)
[2022-08-29 21:46:37,909] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-29 21:46:37,933] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
